### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE error occured

### ISSUE THREAD

**Issue by eujungkim** [cloudfoundry-incubator/cf-abacus-broker#160]
When I push broker, following error occurred.
   2017-11-16T14:49:57.061Z e-abacus-request 65 Request error { message: 'unable to verify the first certificate',
   2017-11-16T23:49:57.06+0900 [APP/PROC/WEB/0] OUT   code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' } - Error: unable to verify the first certificate
   2017-11-16T23:49:57.06+0900 [APP/PROC/WEB/0] OUT     at TLSSocket.<anonymous> (_tls_wrap.js:1108:38)
   2017-11-16T23:49:57.06+0900 [APP/PROC/WEB/0] OUT     at emitNone (events.js:105:13)
   2017-11-16T23:49:57.06+0900 [APP/PROC/WEB/0] OUT     at TLSSocket.emit (events.js:207:7)
   2017-11-16T23:49:57.06+0900 [APP/PROC/WEB/0] OUT     at TLSSocket._finishInit (_tls_wrap.js:638:8)
   2017-11-16T23:49:57.06+0900 [APP/PROC/WEB/0] OUT     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:468:38)

I used commit e46a6aee096a72f2aa2c49526b33a22a7f8ea09a.

**Comment by hsiliev** [comment]
Seems like you are using self-signed certificate. You need to set ‘SKIP_SSL_VALIDATION=true’ environment variable in you app manifests

**Comment by hsiliev** [comment]
@eujungkim Any progress with this one?

**Comment by eujungkim** [comment]
@hsiliev After following your guide, the error does not occur anymore. Thank you for your guide and sorry for my late reply.
So I'll close this issue.

**Comment by hsiliev** [comment]
Glad to hear that skip_ssl_validation works as expected
