### ISSUE TITLE
Invalid redirect error while accessing dashboard url

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-incubator/cf-abacus-broker#63]
Getting following error:

Invalid redirect http://abacus-ext-service-dashboard.apps.<mydomain>.com/ef53222d-e273-4c3f-a740-a1acafdf107c did not match one of the registered values

**Comment by hsiliev** [comment]
Can you please post the broker & dashboard environment (sanitized)?

**Comment by cfmagnum** [comment]
Do you mean "cf env" ?

**Comment by hsiliev** [comment]
Yes please

**Comment by cfmagnum** [comment]
**CF ENV of Broker:**

User-Provided:
API: https://api.mydomain.com
AUTH_SERVER: https://uaa.mydomain.com
BROKER_PASSWORD: pass
BROKER_USER: user
COLLECTOR: http://abacus-usage-collector.mydomain.com
CONF: default
DASHBOARD_REDIRECT_URI: http://abacus-ext-service-dashboard.mydomain.com/redirect
DASHBOARD_URI: http://abacus-ext-service-dashboard.mydomain.com
DEBUG: e-abacus-*,abacus-*,e-*
EUREKA: abacus-eureka-plugin
NODE_MODULES_CACHE: false
NODE_TLS_REJECT_UNAUTHORIZED: 0
PROVISIONING: http://abacus-provisioning-plugin.mydomain.com
SERVICE_BROKER_CLIENT_ID: abacus-broker
SERVICE_BROKER_CLIENT_SECRET: secret

No running env variables have been set

No staging env variables have been set

**CF ENV Of dashboard**

User-Provided:
API: https://api.mydomain.com
AUTH_SERVER: https://uaa.mydomain.com
CF_CLIENT_ID: abacus_db_client
CF_CLIENT_SECRET: secret
CF_COOKIE_SECRET: secret
DEBUG: e-abacus-*,abacus-*,e-*
NODE_TLS_REJECT_UNAUTHORIZED: 0
PROVISIONING: abacus-provisioning-plugin

No running env variables have been set

No staging env variables have been set

**Comment by hsiliev** [comment]
We use `https://*abacus-service-dashboard.cfapps.mydomain.com/manage/instances/*` for `DASHBOARD_REDIRECT_URI`. Can you try with this pattern?

**Comment by cfmagnum** [comment]
Thanks. I'll try and update here.

**Comment by cfmagnum** [comment]
Getting the following error now:

error: Unhandled error: Error
 ERR     at /home/vcap/app/node_modules/passport-oauth2/lib/strategy.js:166:45
 ERR     at /home/vcap/app/node_modules/oauth/lib/oauth2.js:191:18
 ERR     at passBackControl (/home/vcap/app/node_modules/oauth/lib/oauth2.js:132:9)
 ERR     at emitNone (events.js:110:20)
 ERR     at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/oauth/lib/oauth2.js:157:7)
 ERR     at endReadableNT (_stream_readable.js:1045:12)
 ERR     at _combinedTickCallback (internal/process/next_tick.js:102:11)
 ERR     at OAuth2Strategy.parseErrorResponse (/home/vcap/app/node_modules/passport-oauth2/lib/strategy.js:329:12)
 ERR     at IncomingMessage.emit (events.js:207:7)
 ERR     at OAuth2Strategy._createOAuthError (/home/vcap/app/node_modules/passport-oauth2/lib/strategy.js:376:16)
 ERR     at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by abh1kg** [comment]
@cfmagnum : Are you running the application behind a proxy? 
Would it be possible for you to share the output of `uaac client get abacus_db_client`?

**Comment by hsiliev** [comment]
@abh1kg Documented manifest variables and clients in https://github.com/cloudfoundry-incubator/cf-abacus-broker/wiki/Deploying-the-Broker

@cfmagnum Can you please check if the described steps work on your system?

**Comment by cfmagnum** [comment]
@abh1kg Following is the output:

scope: clients.write clients.admin
client_id: abacus_db_client
resource_ids: none
authorized_grant_types: client_credentials authorization_code refresh_token
redirect_uri: https://abacus-ext-service-dashboard.mydomain.com/
autoapprove:
authorities: clients.admin clients.write
name: abacus_db_client

**Comment by abh1kg** [comment]
@cfmagnum Thanks.
The redirect URL for the dashboard client is not registered properly, as @hsiliev pointed out.
You need to run `uaac client update abacus_db_client` to update the redirect_uri to `https://abacus-ext-service-dashboard.mydomain.com/manage/instances/*`

**Comment by cfmagnum** [comment]
Ok

**Comment by cfmagnum** [comment]
Tried with given changes as above. Trying to access dashboard url http://abacus-ext-service-dashboard.mydomain.com/manage/instances/d9d7fa37-15b7-4df0-9d78-cdb6413bfc4a

Getting following error in log:

error: Unhandled error: ReferenceError: debug is not defined
    at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vcap/app/node_modules/express/lib/router/route.js:137:13)
    at router.get (/home/vcap/app/src/routes/ui.js:10:3)
    at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
    at param (/home/vcap/app/node_modules/express/lib/router/index.js:354:14)
    at trim_prefix (/home/vcap/app/node_modules/express/lib/router/index.js:317:13)
    at param (/home/vcap/app/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/vcap/app/node_modules/express/lib/router/index.js:410:3)
    at next (/home/vcap/app/node_modules/express/lib/router/index.js:275:10)
    at Route.dispatch (/home/vcap/app/node_modules/express/lib/router/route.js:112:3)
    at Function.handle (/home/vcap/app/node_modules/express/lib/router/index.js:174:3)
    at router (/home/vcap/app/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
    at /home/vcap/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/vcap/app/node_modules/express/lib/router/index.js:335:12)
    at next (/home/vcap/app/node_modules/express/lib/router/index.js:275:10)
    at initialize (/home/vcap/app/node_modules/passport/lib/middleware/initialize.js:53:5)
    at /home/vcap/app/node_modules/express/lib/router/index.js:284:7
    at next (/home/vcap/app/node_modules/express/lib/router/index.js:275:10)
    at Function.process_params (/home/vcap/app/node_modules/express/lib/router/index.js:335:12)
    at /home/vcap/app/node_modules/express/lib/router/index.js:284:7

**Comment by abh1kg** [comment]
@cfmagnum Can you confirm if the dashboard has the "DEBUG" variable in its environment? And if it does, can you set its value to `abacus-*` and try again.

**Comment by cfmagnum** [comment]
@abh1kg Tried as you told. Still getting same error.

**Comment by cfmagnum** [comment]
resolved "debug error".

Now getting uaac client related error. 

Error:

 ERR debug: CfApiController:: Fetching user permisions
 ERR debug: Sending HTTP request: GET https://api.mydomain.com/v2/service_instances/787f68f0-ffb4-47a7-aaf9- f1d9667917d2/permissions
    ERR error: Unauthorized
    ERR   response:
    ERR { request: 'GET https://api.mydomain.com/v2/service_instances/787f68f0-ffb4-47a7-aaf9-f1d9667917d2/perm
issions',
    ERR    { statusCode: 401,
    ERR      headers:
    ERR      statusMessage: 'Unauthorized',
    ERR       { 'content-type': 'application/json;charset=utf-8',
    ERR         date: 'Thu, 20 Jul 2017 15:06:53 GMT',
    ERR         'x-content-type-options': 'nosniff',
    ERR         server: 'nginx',
    ERR         'x-vcap-request-id': 'c5cc4a4b-38d9-4548-514c-57619014f3d6, d3ea6d78-366a-4a18-531e-4c345367cca3::0e22d7c9-c13a-
442a-964a-848ab15c106b',
    ERR         connection: 'Close' },
    ERR         'content-length': '97',
    ERR       { description: 'Invalid Auth Token',
    ERR      body:
    ERR         error_code: 'CF-InvalidAuthToken',
    ERR error:  Unauthorized: Unauthorized
    ERR         code: 1000 } } }
    ERR     at tryCatcher (/home/vcap/app/node_modules/bluebird/js/release/util.js:16:23)

Kindly let me know the correct statement to add uaa client for dashboard.

**Comment by abh1kg** [comment]
@cfmagnum : The user accessing the dashboard must have the Cloud Foundry Service Permissions scope as described here (https://docs.cloudfoundry.org/services/dashboard-sso.html#checking-user-permissions ).
Can you try with a space developer or the user who created the service instance?

**Comment by hsiliev** [comment]
Closing due to inactivity. Please reopen if you still experience problems.
